### ISSUE TITLE
CLI Gas Allowance Function

### ISSUE THREAD

**Issue by Mr-biii** [5afe/safe-cli#217]
I am trying to send some erc 20 tokens (USDC in this case) out of an Optimism safe. I have loaded the safe and the owners but when I use the "send erc-20" function I get a gas related error:

blockchain > 0xffb17DbBa1C2cc4A1D678750D307a07b7990F6d6 > send_erc20 0x7F5c764cBc14f9669B88837ca1490cCa17c31607 0x1d****ab4Bc 1
Result: True
Do you want to execute tx SafeTx - safe=0xffb17DbBa1C2cc4A1D678750D307a07b7990F6d6 - to=0x1d****ab4Bc - value=0 - data=0xa9059cbb0000000000000000000000007f5c764cbc14f9669b88837ca1490cca17c316070000000000000000000000000000000000000000000000000000000000000001 - operation=0 - safe-tx-gas=0 - base-gas=0 - gas-price=0 - gas-token=0x0000000000000000000000000000000000000000 - refund-receiver=0x0000000000000000000000000000000000000000 - signers = ['0x6D12D01f9218a736B45d5eF61Bf7616a3B00F621'] [y/N]: y
Traceback (most recent call last):
  File "/usr/local/bin/safe-cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/safe_cli/main.py", line 150, in main
    safe_cli.loop()
  File "/usr/local/lib/python3.10/site-packages/safe_cli/main.py", line 135, in loop
    self.prompt_parser.process_command(command)
  File "/usr/local/lib/python3.10/site-packages/safe_cli/prompt_parser.py", line 173, in process_command
    return args.func(args)
  File "/usr/local/lib/python3.10/site-packages/safe_cli/prompt_parser.py", line 79, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/safe_cli/prompt_parser.py", line 245, in send_erc20
    safe_operator.send_erc20(
  File "/usr/local/lib/python3.10/site-packages/safe_cli/operators/safe_operator.py", line 461, in send_erc20
    return self.send_custom(
  File "/usr/local/lib/python3.10/site-packages/safe_cli/operators/safe_operator.py", line 448, in send_custom
    return self.prepare_and_execute_safe_transaction(
  File "/usr/local/lib/python3.10/site-packages/safe_cli/operators/safe_operator.py", line 731, in prepare_and_execute_safe_transaction
    return self.execute_safe_transaction(safe_tx)
  File "/usr/local/lib/python3.10/site-packages/safe_cli/operators/safe_operator.py", line 174, in decorated
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/safe_cli/operators/safe_operator.py", line 739, in execute_safe_transaction
    tx_hash, tx = safe_tx.execute(
  File "/usr/local/lib/python3.10/site-packages/gnosis/safe/safe_tx.py", line 380, in execute
    self.tx = self.w3_tx.build_transaction(tx_parameters)
  File "/usr/local/lib/python3.10/site-packages/web3/contract.py", line 1099, in build_transaction
    return build_transaction_for_function(
  File "/usr/local/lib/python3.10/site-packages/web3/contract.py", line 1711, in build_transaction_for_function
    prepared_transaction = fill_transaction_defaults(web3, prepared_transaction)
  File "cytoolz/functoolz.pyx", line 249, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.10/site-packages/web3/_utils/transactions.py", line 114, in fill_transaction_defaults
    default_val = default_getter(web3, transaction)
  File "/usr/local/lib/python3.10/site-packages/web3/_utils/transactions.py", line 60, in <lambda>
    'gas': lambda web3, tx: web3.eth.estimate_gas(tx),
  File "/usr/local/lib/python3.10/site-packages/web3/eth.py", line 868, in estimate_gas
    return self._estimate_gas(transaction, block_identifier)
  File "/usr/local/lib/python3.10/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/usr/local/lib/python3.10/site-packages/web3/manager.py", line 198, in request_blocking
    return self.formatted_response(response,
  File "/usr/local/lib/python3.10/site-packages/web3/manager.py", line 171, in formatted_response
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'gas required exceeds allowance (550000000)'}

So I tried to modify the by adding these functions to the command: "--gas 600000 --gasPrice 20" but it still doesn't work. It give the "unrecognized argument" error.

blockchain > 0xffb17DbBa1C2cc4A1D678750D307a07b7990F6d6 > send_erc20 0x7F5c764cBc14f9669B88837ca1490cCa17c31607 0x1d****ab4Bc 1 --gas 600000 --gasPrice 20
usage:  [-h] {show_cli_owners,load_cli_owners_from_words,load_cli_owners,unload_cli_owners,change_threshold,approve_hash,add_owner,remove_owner,change_fallback_handler,change_guard,change_master_copy,update,send_custom,send_ether,send_erc20,send_erc721,drain,get_threshold,get_nonce,get_owners,enable_module,disable_module,info,refresh,balances,history,sign-tx,batch-txs,execute-tx,get_delegates,add_delegate,remove_delegate}
        ...
: error: unrecognized arguments: --gas 600000 --gasPrice 20

Clearly, there is a problem with the command. How can I fix it? Any help would be much appreciated!

**Comment by Dawidowak** [comment]
Omco chodzi dlaczefo zmiany ?

**Comment by mmv08** [comment]
@Uxio0 I've answered this issue here https://ethereum.stackexchange.com/questions/149426/gnosis-safe-cli-gas-allowance-function therefore we can close the issue
