### ISSUE TITLE
Cannot commence on BSC

### ISSUE THREAD

**Issue by 0xBaneZ** [5afe/safe-cli#236]
I have a mannually created safe address on BSC via the 1.1.1 contract. 

While for the same address, following the same creation method, can all well commence on SAFE-CLI on polygon, goreli testnet etc, only for BSC, After I input:
```
safe-cli 0xB18e3BF33365fD2466c2E99b181E527a165c210c https://bscrpc.com
```
It shows up with:
```
Traceback (most recent call last):
  File "/home/codespace/.local/lib/python3.10/site-packages/web3/contract/utils.py", line 111, in call_contract_function
    output_data = w3.codec.decode(output_types, return_data)
  File "/home/codespace/.local/lib/python3.10/site-packages/eth_abi/codec.py", line 149, in decode
    return decoder(stream)
  File "/home/codespace/.local/lib/python3.10/site-packages/eth_abi/decoding.py", line 128, in __call__
    return self.decode(stream)
  File "/home/codespace/.local/lib/python3.10/site-packages/eth_utils/functional.py", line 45, in inner
    return callback(fn(*args, **kwargs))
  File "/home/codespace/.local/lib/python3.10/site-packages/eth_abi/decoding.py", line 174, in decode
    yield decoder(stream)
  File "/home/codespace/.local/lib/python3.10/site-packages/eth_abi/decoding.py", line 128, in __call__
    return self.decode(stream)
  File "/home/codespace/.local/lib/python3.10/site-packages/eth_abi/decoding.py", line 143, in decode
    start_pos = decode_uint_256(stream)
  File "/home/codespace/.local/lib/python3.10/site-packages/eth_abi/decoding.py", line 128, in __call__
    return self.decode(stream)
  File "/home/codespace/.local/lib/python3.10/site-packages/eth_abi/decoding.py", line 198, in decode
    raw_data = self.read_data_from_stream(stream)
  File "/home/codespace/.local/lib/python3.10/site-packages/eth_abi/decoding.py", line 305, in read_data_from_stream
    raise InsufficientDataBytes(
eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/codespace/.python/current/bin/safe-cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/safe_cli/main.py", line 150, in main
    safe_cli = SafeCli()
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/safe_cli/main.py", line 52, in __init__
    self.safe_operator = SafeOperator(safe_address, node_url)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/safe_cli/operators/safe_operator.py", line 197, in __init__
    self.safe_contract = self.safe.contract
  File "/usr/local/python/3.10.8/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/codespace/.local/lib/python3.10/site-packages/gnosis/safe/safe.py", line 114, in contract
    version = v_1_3_0_contract.functions.VERSION().call()
  File "/home/codespace/.local/lib/python3.10/site-packages/web3/contract/contract.py", line 283, in call
    return call_contract_function(
  File "/home/codespace/.local/lib/python3.10/site-packages/web3/contract/utils.py", line 129, in call_contract_function
    raise BadFunctionCallOutput(msg) from e
web3.exceptions.BadFunctionCallOutput: Could not decode contract function call to VERSION with return data: b'', output_types: ['string']
```
How to solve it? Many thanks.

**Comment by Uxio0** [comment]
Safe CLI cannot be used as the Safe Master Copy 1.1.1 is not deployed on BSC (and cannot be deployed as the deployer account was used already and `nonce=0` was required to deploy), so your Safe is not initialized and it's stuck. I'm afraid there's nothing that can be done about it
