### ISSUE TITLE
Cannot launch the CLI: `AttributeError: type object 'Web3' has no attribute 'toChecksumAddress'`

### ISSUE THREAD

**Issue by mmv08** [5afe/safe-cli#244]
**Describe the bug**
When launching the CLI, the following error is thrown:
```
Traceback (most recent call last):
  File "/Users/mmv/.pyenv/versions/3.10.12/bin/safe-cli", line 5, in <module>
    from safe_cli.main import main
  File "/Users/mmv/.pyenv/versions/3.10.12/lib/python3.10/site-packages/safe_cli/main.py", line 37, in <module>
    args = parser.parse_args()
  File "/Users/mmv/.pyenv/versions/3.10.12/lib/python3.10/argparse.py", line 1833, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/Users/mmv/.pyenv/versions/3.10.12/lib/python3.10/argparse.py", line 1866, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/Users/mmv/.pyenv/versions/3.10.12/lib/python3.10/argparse.py", line 2082, in _parse_known_args
    stop_index = consume_positionals(start_index)
  File "/Users/mmv/.pyenv/versions/3.10.12/lib/python3.10/argparse.py", line 2038, in consume_positionals
    take_action(action, args)
  File "/Users/mmv/.pyenv/versions/3.10.12/lib/python3.10/argparse.py", line 1927, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/Users/mmv/.pyenv/versions/3.10.12/lib/python3.10/argparse.py", line 2462, in _get_values
    value = self._get_value(action, arg_string)
  File "/Users/mmv/.pyenv/versions/3.10.12/lib/python3.10/argparse.py", line 2495, in _get_value
    result = type_func(arg_string)
  File "/Users/mmv/.pyenv/versions/3.10.12/lib/python3.10/site-packages/safe_cli/prompt_parser.py", line 70, in to_checksummed_ethereum_address
    return Web3.toChecksumAddress(address)
AttributeError: type object 'Web3' has no attribute 'toChecksumAddress'. Did you mean: 'to_checksum_address'?
```

**To Reproduce**
1. Install the cli `pip install safe-cli`
2. Launche the cli `safe-cli <address> <rpc_url>`

**Expected behavior**
The cli launches fine and useable.

**Additional context**
OS - MacOS 13.5
Python - 3.10.12

**Comment by ptqa** [comment]
Yeah, this update was not completed correctly https://github.com/5afe/safe-cli/commit/b3425100419451041dafb5f296df95291c46a6d1
