### ISSUE TITLE
Cannot use change_master_copy

### ISSUE THREAD

**Issue by divine-comedian** [5afe/safe-cli#246]
### Describe the bug

**OS: Ubuntu 22.04** 

I need to troubleshoot and fix an existing multisig - currently having issues because it was initialized using an old proxy version - which I think causes bad behaviour on the web interface. 

I want to change the master_copy to the correct one but doing it through the CLI seems to be impossible. If I use change_master_copy it requires me to have enough PKs loaded to sign the tx - which is frankly ridiculous that I would have multiple private keys belonging to other signers on my machine or in my possession. 

try to submit with tx-service - enter tx-service on optimism, attempt to submit, app crashes with python error:

```
blockchain > 0xf924fF0f192f0c7c073161e0d62CE7635114e74f > tx-service
Sending txs to tx service
tx-service > 0xf924fF0f192f0c7c073161e0d62CE7635114e74f > change_master_copy 0xfb1bffC9d739B8D520DaF37dF666da4C6871
91EA
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/safe_cli/prompt_parser.py", line 79, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/safe_cli/prompt_parser.py", line 223, in change_master_copy
    safe_operator.change_master_copy(args.address)
  File "/usr/local/lib/python3.10/site-packages/safe_cli/operators/safe_operator.py", line 527, in change_master_copy
    if self.execute_safe_internal_transaction(transaction["data"]):
  File "/usr/local/lib/python3.10/site-packages/safe_cli/operators/safe_operator.py", line 704, in execute_safe_internal_transaction
    return self.prepare_and_execute_safe_transaction(self.address, 0, data)
  File "/usr/local/lib/python3.10/site-packages/safe_cli/operators/safe_tx_service_operator.py", line 268, in prepare_and_execute_safe_transaction
    safe_tx = self.prepare_safe_transaction(
  File "/usr/local/lib/python3.10/site-packages/safe_cli/operators/safe_operator.py", line 717, in prepare_safe_transaction
    self.sign_transaction(safe_tx)  # Raises exception if it cannot be signed
  File "/usr/local/lib/python3.10/site-packages/safe_cli/operators/safe_operator.py", line 849, in sign_transaction
    permitted_signers = self.get_permitted_signers()
  File "/usr/local/lib/python3.10/site-packages/safe_cli/operators/safe_tx_service_operator.py", line 292, in get_permitted_signers
    for row in self.safe_tx_service.get_delegates(self.address)
  File "/usr/local/lib/python3.10/site-packages/safe_cli/api/transaction_service_api.py", line 148, in get_delegates
    raise BaseAPIException(f"Cannot get delegates: {response.content}")
safe_cli.api.base_api.BaseAPIException: Cannot get delegates: b'\n<!doctype html>\n<html lang="en">\n<head>\n  <title>Not Found</title>\n</head>\n<body>\n  <h1>Not Found</h1><p>The requested resource was not found on this server.</p>\n</body>\n</html>\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/safe-cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/safe_cli/main.py", line 150, in main
    safe_cli.loop()
  File "/usr/local/lib/python3.10/site-packages/safe_cli/main.py", line 135, in loop
    self.prompt_parser.process_command(command)
  File "/usr/local/lib/python3.10/site-packages/safe_cli/prompt_parser.py", line 173, in process_command
    return args.func(args)
  File "/usr/local/lib/python3.10/site-packages/safe_cli/prompt_parser.py", line 82, in wrapper
    print_formatted_text(HTML(f"<b><ansired>{e.args[0]}</ansired></b>"))
  File "/usr/local/lib/python3.10/site-packages/prompt_toolkit/formatted_text/html.py", line 35, in __init__
    document = minidom.parseString(f"<html-root>{value}</html-root>")
  File "/usr/local/lib/python3.10/xml/dom/minidom.py", line 2000, in parseString
    return expatbuilder.parseString(string)
  File "/usr/local/lib/python3.10/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/usr/local/lib/python3.10/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 51                                
```

**To Reproduce**
1. Connect w/ docker on CLI - enter multisig address & rpc node (Optimism this case)
2. load my private key as one of the signers load_cli_owner .... 
3. change_master_copy 0xfb1bffC9d739B8D520DaF37dF666da4C687191EA
4. Receive error not enough signers (multisig is 7/15)

**OR** 

Follow steps 1 & 2 
3. enter tx-service 
4. change_master_copy 0xfb1bffC9d739B8D520DaF37dF666da4C687191EA
5. python error - app crashes

**Expected behavior**
I should be able to generate a multisig vote to change the master copy from the CLI since no options exist on the web interface 

**Additional context**
I have updated my code to the latest on master branch - not sure why this is broken - I've had many issues using the tx-service and the CLI in general crashing with python errors.

**Comment by Uxio0** [comment]
You are right, we are addressing it now

**Comment by divine-comedian** [comment]
What was the fix? Do I need to do anything different or should it work as I am trying to do it in the steps above?

**Comment by Uxio0** [comment]
It should work, just update to the latest version

**Comment by divine-comedian** [comment]
@Uxio0 
I pulled to the latest version (commit `41c4db3bce4eb8b2417b6f8ef26b09606e05fb31` on `master`) and it still fails when trying to use the tx-service on Optimism

```
tx-service > 0xf924fF0f192f0c7c073161e0d62CE7635114e74f > change_master_copy 0xfb1b
ffC9d739B8D520DaF37dF666da4C687191EA
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/safe_cli/prompt_parser.py", line 79, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/safe_cli/prompt_parser.py", line 223, in change_master_copy
    safe_operator.change_master_copy(args.address)
  File "/usr/local/lib/python3.10/site-packages/safe_cli/operators/safe_operator.py", line 527, in change_master_copy
    if self.execute_safe_internal_transaction(transaction["data"]):
  File "/usr/local/lib/python3.10/site-packages/safe_cli/operators/safe_operator.py", line 704, in execute_safe_internal_transaction
    return self.prepare_and_execute_safe_transaction(self.address, 0, data)
  File "/usr/local/lib/python3.10/site-packages/safe_cli/operators/safe_tx_service_operator.py", line 268, in prepare_and_execute_safe_transaction
    safe_tx = self.prepare_safe_transaction(
  File "/usr/local/lib/python3.10/site-packages/safe_cli/operators/safe_operator.py", line 717, in prepare_safe_transaction
    self.sign_transaction(safe_tx)  # Raises exception if it cannot be signed
  File "/usr/local/lib/python3.10/site-packages/safe_cli/operators/safe_operator.py", line 849, in sign_transaction
    permitted_signers = self.get_permitted_signers()
  File "/usr/local/lib/python3.10/site-packages/safe_cli/operators/safe_tx_service_operator.py", line 292, in get_permitted_signers
    for row in self.safe_tx_service.get_delegates(self.address)
  File "/usr/local/lib/python3.10/site-packages/safe_cli/api/transaction_service_api.py", line 148, in get_delegates
    raise BaseAPIException(f"Cannot get delegates: {response.content}")
safe_cli.api.base_api.BaseAPIException: Cannot get delegates: b'\n<!doctype html>\n<html lang="en">\n<head>\n  <title>Not Found</title>\n</head>\n<body>\n  <h1>Not Found</h1><p>The requested resource was not found on this server.</p>\n</body>\n</html>\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/safe-cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/safe_cli/main.py", line 150, in main
    safe_cli.loop()
  File "/usr/local/lib/python3.10/site-packages/safe_cli/main.py", line 135, in loop
    self.prompt_parser.process_command(command)
  File "/usr/local/lib/python3.10/site-packages/safe_cli/prompt_parser.py", line 173, in process_command
    return args.func(args)
  File "/usr/local/lib/python3.10/site-packages/safe_cli/prompt_parser.py", line 82, in wrapper
    print_formatted_text(HTML(f"<b><ansired>{e.args[0]}</ansired></b>"))
  File "/usr/local/lib/python3.10/site-packages/prompt_toolkit/formatted_text/html.py", line 35, in __init__
    document = minidom.parseString(f"<html-root>{value}</html-root>")
  File "/usr/local/lib/python3.10/xml/dom/minidom.py", line 2000, in parseString
    return expatbuilder.parseString(string)
  File "/usr/local/lib/python3.10/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/usr/local/lib/python3.10/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 51
```

**Comment by Uxio0** [comment]
Can you check you are indeed using v0.7.1 of safe-cli? (it should show up on start)

**Comment by divine-comedian** [comment]
> Can you check you are indeed using v0.7.1 of safe-cli? (it should show up on start)

![image](https://github.com/5afe/safe-cli/assets/67759413/642e8607-43eb-4974-a8d4-f94ff130dc85)

Doesn't look like it - still shows v0.7.0 - but it doesn't seem to be updating at least on the interface. I've tried git pulling from terminal & from VScode 

I also deleted and downloaded a fresh copy from the repo.. and ran it using the docker script

Am I missing something here?

**Comment by Uxio0** [comment]
Did you do `pip3 install -U safe-cli`?

**Comment by divine-comedian** [comment]
> Did you do `pip3 install -U safe-cli`?

Okay! tried it out using local install and it appears to work! Thanks for the fix. 

Would it be possible to update the docker script so it runs the correct versrion?

**Comment by Uxio0** [comment]
Our docker image is updated

**Comment by divine-comedian** [comment]
Thanks! I was able to generate the tx however it looks like it is unexecutable once signed - I'm not sure where or if to make another issue but this one here probably has the most context... 

The simulation says it will be reverted and does not provide a reason
https://app.safe.global/transactions/tx?safe=oeth:0xf924fF0f192f0c7c073161e0d62CE7635114e74f&id=multisig_0xf924fF0f192f0c7c073161e0d62CE7635114e74f_0x1444fccd782980fd2bc3f3464abd903cf04a686819855db9b0d89ad1e6c64ea4

Trying to upgrade this safe:
https://optimistic.etherscan.io/address/0xf924fF0f192f0c7c073161e0d62CE7635114e74f

To this implementation:
https://optimistic.etherscan.io/address/0xfb1bffC9d739B8D520DaF37dF666da4C687191EA


When I try to excute the tx using the CLI the app crashes:
```
tx-service > 0xf924fF0f192f0c7c073161e0d62CE7635114e74f > execute-tx 0x1444fccd7
82980fd2bc3f3464abd903cf04a686819855db9b0d89ad1e6c64ea4
Traceback (most recent call last):
  File "/home/mitch/anaconda3/lib/python3.9/site-packages/gnosis/safe/safe_tx.py", line 304, in call
    success = self.w3_tx.call(parameters, block_identifier=block_identifier)
  File "/home/mitch/anaconda3/lib/python3.9/site-packages/web3/contract/contract.py", line 283, in call
    return call_contract_function(
  File "/home/mitch/anaconda3/lib/python3.9/site-packages/web3/contract/utils.py", line 96, in call_contract_function
    return_data = w3.eth.call(
  File "/home/mitch/anaconda3/lib/python3.9/site-packages/web3/eth/eth.py", line 256, in call
    return self._durin_call(transaction, block_identifier, state_override)
  File "/home/mitch/anaconda3/lib/python3.9/site-packages/web3/eth/eth.py", line 275, in _durin_call
    return self._call(transaction, block_identifier, state_override)
  File "/home/mitch/anaconda3/lib/python3.9/site-packages/web3/module.py", line 73, in caller
    result = w3.manager.request_blocking(
  File "/home/mitch/anaconda3/lib/python3.9/site-packages/web3/manager.py", line 250, in request_blocking
    return self.formatted_response(
  File "/home/mitch/anaconda3/lib/python3.9/site-packages/web3/manager.py", line 209, in formatted_response
    apply_error_formatters(error_formatters, response)
  File "/home/mitch/anaconda3/lib/python3.9/site-packages/web3/manager.py", line 85, in apply_error_formatters
    formatted_resp = pipe(response, error_formatters)
  File "cytoolz/functoolz.pyx", line 667, in cytoolz.functoolz.pipe
  File "cytoolz/functoolz.pyx", line 642, in cytoolz.functoolz.c_pipe
  File "/home/mitch/anaconda3/lib/python3.9/site-packages/web3/_utils/contract_error_handling.py", line 139, in raise_contract_logic_error_on_revert
    raise ContractLogicError(message, data=data)
web3.exceptions.ContractLogicError: execution reverted: GS013

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mitch/anaconda3/bin/safe-cli", line 8, in <module>
    sys.exit(main())
  File "/home/mitch/anaconda3/lib/python3.9/site-packages/safe_cli/main.py", line 152, in main
    safe_cli.loop()
  File "/home/mitch/anaconda3/lib/python3.9/site-packages/safe_cli/main.py", line 137, in loop
    self.prompt_parser.process_command(command)
  File "/home/mitch/anaconda3/lib/python3.9/site-packages/safe_cli/prompt_parser.py", line 173, in process_command
    return args.func(args)
  File "/home/mitch/anaconda3/lib/python3.9/site-packages/safe_cli/prompt_parser.py", line 79, in wrapper
    return function(*args, **kwargs)
  File "/home/mitch/anaconda3/lib/python3.9/site-packages/safe_cli/prompt_parser.py", line 309, in execute_tx
    safe_operator.execute_tx(args.safe_tx_hash)
  File "/home/mitch/anaconda3/lib/python3.9/site-packages/safe_cli/operators/safe_tx_service_operator.py", line 203, in execute_tx
    return self.execute_safe_transaction(safe_tx)
  File "/home/mitch/anaconda3/lib/python3.9/site-packages/safe_cli/operators/safe_operator.py", line 174, in decorated
    return f(self, *args, **kwargs)
  File "/home/mitch/anaconda3/lib/python3.9/site-packages/safe_cli/operators/safe_operator.py", line 736, in execute_safe_transaction
    call_result = safe_tx.call(self.default_sender.address)
  File "/home/mitch/anaconda3/lib/python3.9/site-packages/gnosis/safe/safe_tx.py", line 313, in call
    return self._raise_safe_vm_exception(str(exc))
  File "/home/mitch/anaconda3/lib/python3.9/site-packages/gnosis/safe/safe_tx.py", line 282, in _raise_safe_vm_exception
    raise custom_exception(message)
gnosis.safe.exceptions.SafeTransactionFailedWhenGasPriceAndSafeTxGasEmpty: execution reverted: GS013
```

**Comment by Uxio0** [comment]
Currently only updating from versions < 1.3.0 to 1.3.0 is supported. Btw, migrating from 1.3.0 to 1.3.0L2 will not make your Safe compatible with the official UI, it needs to be deployed as a L2 due to the indexer will be missing Safe creation information that's needed to build the Safe history
